name: rick_and_morty_app
description: Flutter + Get + Graphql

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.12.1
  graphql_flutter: ^3.1.0
  meta: ^1.1.8
  path_provider: ^1.6.18
  lumberdash: ^2.1.1
  colorize_lumberdash: ^2.1.0
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.1
  bloc_test: ^7.0.4
  network_image_mock: ^1.0.0
  test_coverage: ^0.4.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
